options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Stap 1: Bouw de Docker-image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-garmin-oauth', '.']

  # Stap 2: Push de Docker-image naar Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-garmin-oauth']

  # Stap 3: Deploy naar Cloud Run met omgevingsvariabelen
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'flask-garmin-oauth'
      - '--image'
      - 'gcr.io/$PROJECT_ID/flask-garmin-oauth'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'CLIENT_ID=${_CLIENT_ID},CLIENT_SECRET=${_CLIENT_SECRET},FLASK_SECRET_KEY=${_FLASK_SECRET_KEY},REDIRECT_URI=${_REDIRECT_URI}'

substitutions:
  _CLIENT_ID: 'default_client_id'
  _CLIENT_SECRET: 'default_client_secret'
  _FLASK_SECRET_KEY: 'default_flask_secret'
  _REDIRECT_URI: 'https://default-redirect-uri'
