options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-garmin-oauth', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-garmin-oauth']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'flask-garmin-oauth'
      - '--image'
      - 'gcr.io/$PROJECT_ID/flask-garmin-oauth'
      - '--platform'
      - 'managed'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'USERNAME=${_USERNAME},PASSWORD=${_PASSWORD}'

substitutions:
  _USERNAME: 'jouw_email@voorbeeld.com'
  _PASSWORD: 'jouw_wachtwoord'
